spring.application.name=FoodApp

server.port=8090




# MYSQL PRODUCTION CONNECTION
spring.datasource.url=/fooddb
spring.datasource.username=admin
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none





secreteJwtString=food123456789


## Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


## AWS CONFIG
aws.s3.region=eu-north-1
aws.s3.bucket=foodapp-abcd
aws.accessKeyId=
aws.secretKey=





##LOCAL REACT FRONTEND
base.payment.link=http://foodapp-de/pay?orderid=
frontend.base.url=


spring.web.locale=en_IN

##STRIP CREDENTIALS
stripe.api.public.key=
stripe.api.secret.key=




